apiVersion: apps/v1
kind: Deployment
metadata:
  name: purchase-order
  labels:
    app: purchase-order
spec:
  replicas: 1
  template:
    metadata:
      name: purchase-order
      labels:
        app: purchase-order
    spec:
      containers:
        - name: purchase-order
          image: untucapital/purchase-order:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
      restartPolicy: Always
  selector:
    matchLabels:
      app: purchase-order
