apiVersion: apps/v1
kind: Deployment
metadata:
  name: musoni-service
  labels:
    app: musoni-service
spec:
  replicas: 1
  template:
    metadata:
      name: musoni-service
      labels:
        app: musoni-service
    spec:
      containers:
        - name: musoni-service
          image: untucapital/musoni-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
      restartPolicy: Always
  selector:
    matchLabels:
      app: musoni-service
