apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-ms
  labels:
    app: credit-ms
spec:
  replicas: 1
  template:
    metadata:
      name: credit-ms
      labels:
        app: credit-ms
    spec:
      containers:
        - name: credit-ms
          image: untucapital/credit-ms:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8086
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
      restartPolicy: Always
  selector:
    matchLabels:
      app: credit-ms
