apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        deployment.kubernetes.io/revision: "1"
        kubectl.kubernetes.io/last-applied-configuration: |
            {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"credit-ms"},"name":"credit-ms-deployment","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"credit-ms"}},"template":{"metadata":{"labels":{"app":"credit-ms"}},"spec":{"containers":[{"image":"credit-ms:1.0.0","name":"credit-ms","ports":[{"containerPort":8086}]}]}}}}
    creationTimestamp: "2020-01-24T10:54:56Z"
    generation: 1
    labels:
        app: credit-ms
    name: credit-ms-deployment
    namespace: default
    resourceVersion: "96574"
    selfLink: /apis/apps/v1/namespaces/default/deployments/credit-ms-deployment
    uid: e1075fa3-6468-43d0-83c0-63fede0dae51
spec:
    progressDeadlineSeconds: 600
    replicas: 2
    revisionHistoryLimit: 10
    selector:
        matchLabels:
            app: credit-ms
    strategy:
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
        type: RollingUpdate
    template:
        metadata:
            creationTimestamp: null
            labels:
                app: credit-ms
        spec:
            containers:
                - image: credit-ms:1.0.0
                  imagePullPolicy: IfNotPresent
                  name: credit-ms
                  ports:
                      - containerPort: 8086
                        protocol: TCP
                  resources: {}
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
            dnsPolicy: ClusterFirst
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
status:
    availableReplicas: 2
    conditions:
        - lastTransitionTime: "2020-01-24T10:54:59Z"
          lastUpdateTime: "2020-01-24T10:54:59Z"
          message: Deployment has minimum availability.
          reason: MinimumReplicasAvailable
          status: "True"
          type: Available
        - lastTransitionTime: "2020-01-24T10:54:56Z"
          lastUpdateTime: "2020-01-24T10:54:59Z"
          message: ReplicaSet "credit-ms-deployment-7d64f4b574" has successfully progressed.
          reason: NewReplicaSetAvailable
          status: "True"
          type: Progressing
    observedGeneration: 1
    readyReplicas: 2
    replicas: 2
    updatedReplicas: 2

---
apiVersion: v1
kind: Service
metadata:
  name: credit-ms-service
spec:
  selector:
    app: credit-ms
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086

